### ISSUE TITLE
Beta 16 support tracker for @flarum

### ISSUE THREAD

**Issue by luceos** [FriendsOfFlarum/ban-ips#15]
Pending support for beta 16. This issue can be closed when upgraded, so that we can upgrade discuss.

/cc @jordanjay29

![image](https://user-images.githubusercontent.com/504687/115832405-2a8ab780-a413-11eb-810f-2404cb85f1bd.png)

**Comment by imorland** [comment]
We won't be releasing an update for beta 16 of this extension, although this issue will be resolved in the `1.0.0` release
