### ISSUE TITLE
Ban button in profile is not working.

### ISSUE THREAD

**Issue by xasha32** [FriendsOfFlarum/ban-ips#20]
Uncaught ReferenceError: post is not defined                                                                         addBanIPControl.js:42 
    at HTMLButtonElement.onclick (addBanIPControl.js:42)
    at $.handleEvent (render.js:888)
onclick @ addBanIPControl.js:42
$.handleEvent @ render.js:888

Browser Console error img  link -  https://telegra.ph/file/2ba4b05d5970eeaa04bb4.png

**Comment by datitisev** [comment]
Fixed in v1.0.1
