### ISSUE TITLE
Base table or view already exists: Table 'banned_ips'

### ISSUE THREAD

**Issue by iPurpl3x** [FriendsOfFlarum/ban-ips#21]
## Bug Report

**Current Behavior**
PDOException: SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'banned_ips' 

**Steps to Reproduce**
1. Initially I don't know but the extension was disabled
2. Activate the extension from the admin panel

**Expected Behavior**
No error

**Environment**
- Flarum version: 1.0.4
- Extension version: 1.0.0
- Hosting environment: local

**Possible solution(s)**

Adjust the code of the migration where this table is created to handle situations where the DB already contains the table.

**Comment by dsevillamartin** [comment]
The migration should not need to account for existing table because it should only run once on an installation... This issue sometimes pops up on other exts as well so it might be a core issues but i don't think we have enough info to figure out what the root cause is.
