### ISSUE TITLE
very slow

### ISSUE THREAD

**Issue by krodelabestiole** [FriendsOfFlarum/ban-ips#23]
hello, i'm currently testing to migrate a big forum on flarum and the whole thing is responding VERY slowly as soon as ban-ips is activated...
(in the admin area as well as the front)

is there any reason for that ? any way to improve performances ?

here is the testing forum : https://ufr-forum.crachecode.net/

**Comment by imorland** [comment]
I've recently noticed this too. I'll tackle this as soon as possible
